%define debug_package %{nil}

%define package_name 	gcc
%define package_family	gcc48
%define package_type 	compilers
%define software_path	/opt/software
%define package_path	%{software_path}/%{package_type}/%{package_family}

Summary: Various compilers
Name: %{package_type}-%{package_family}-%{package_name}
Version: 4.8.3
Release: 1%{?dist}
License: GPLv3+ and GPLv3+ with exceptions and GPLv2+ with exceptions
Group: Development/Languages
Source: %{package_name}-%{version}.tar.gz
URL: http://gcc.gnu.org
Vendor: CentOS
Packager: Rob Lyon <rob.lyon@wsu.edu>
Buildroot: %{_tmppath}/%{name}-%{version}-%{release}-root
BuildRequires: Lmod
BuildRequires: compilers-%{package_family}-gmp
BuildRequires: compilers-%{package_family}-mpfr
BuildRequires: compilers-%{package_family}-mpc
BuildRequires: compilers-%{package_family}-isl
BuildRequires: compilers-%{package_family}-cloog
BuildRequires: compilers-%{package_family}-zlib
Requires: Lmod
Requires: compilers-%{package_family}-gmp
Requires: compilers-%{package_family}-mpfr
Requires: compilers-%{package_family}-mpc
Requires: compilers-%{package_family}-isl
Requires: compilers-%{package_family}-cloog
Requires: compilers-%{package_family}-zlib

%description
The gcc package contains the GNU Compiler Collection

%prep
%setup -q -n %{package_name}-%{version}

%build
# export PATH=%{package_path}:$PATH
# export LD_LIBRARY_PATH=%{package_path}/lib:$LD_LIBRARY_PATH
# export CFLAGS="-L%{package_path}/lib -I%{package_path}/include %{optflags}"
# export CPPFLAGS="$CFLAGS -pedantic"
# export CXXFLAGS="$CFLAGS -pedantic"
# export LDFLAGS="-L%{package_path}/lib %{optflags}"

mkdir build ; pushd build
export LD_LIBRARY_PATH=%{package_path}/lib

CC="$CC" \
CFLAGS="$OPT_FLAGS -L%{package_path}/lib -I%{package_path}/include" \
CXXFLAGS="`echo " $CFLAGS " | sed 's/ -Wall / /g;s/ -fexceptions / /g' \
	| sed 's/ -Werror=format-security / -Wformat -Werror=format-security /'`" \
../configure 	--prefix=%{package_path} \
				--disable-multilib \
				--enable-shared \
				--enable-__cxa_atexit \
				--enable-checking=release \
				--enable-lto \
				--enable-threads=posix \
				--enable-languages=c,c++,objc,obj-c++,fortran \
				--disable-libunwind-exceptions \
				--disable-libstdcxx-pch \
				--disable-werror \
				--disable-libgcj \
				--disable-libmudflap \
				--disable-nls \
				--with-fpmath=sse \
				--with-system-zlib \
				--with-cpu=generic \
				--with-gmp=%{package_path} \
				--with-mpfr=%{package_path} \
				--with-mpc=%{package_path} \
				--with-isl=%{package_path} \
				--with-cloog=%{package_path} \
				--build=x86_64-redhat-linux
make -j3
popd

%install
# export PATH=%{package_path}:$PATH
# export LD_LIBRARY_PATH=%{package_path}/lib:$LD_LIBRARY_PATH
# export CFLAGS="-L%{package_path}/lib -I%{package_path}/include %{optflags}"
# export CPPFLAGS="$CFLAGS -pedantic"
# export CXXFLAGS="$CFLAGS -pedantic"
# export LDFLAGS="-L%{package_path}/lib %{optflags}"

pushd build
make DESTDIR=%{buildroot} install
rm -rf %{buildroot}/%{package_path}/share/info/dir
popd

# Add cpp and cc links

%files
%defattr(-,root,root)
%{package_path}/bin/c++
%{package_path}/bin/cpp
%{package_path}/bin/g++
%{package_path}/bin/gcc
%{package_path}/bin/gcc-ar
%{package_path}/bin/gcc-nm
%{package_path}/bin/gcc-ranlib
%{package_path}/bin/gcov
%{package_path}/bin/gfortran
%{package_path}/bin/x86_64-redhat-linux-c++
%{package_path}/bin/x86_64-redhat-linux-g++
%{package_path}/bin/x86_64-redhat-linux-gcc
%{package_path}/bin/x86_64-redhat-linux-gcc-4.8.3
%{package_path}/bin/x86_64-redhat-linux-gcc-ar
%{package_path}/bin/x86_64-redhat-linux-gcc-nm
%{package_path}/bin/x86_64-redhat-linux-gcc-ranlib
%{package_path}/bin/x86_64-redhat-linux-gfortran
%{package_path}/include/c++/4.8.3/algorithm
%{package_path}/include/c++/4.8.3/array
%{package_path}/include/c++/4.8.3/atomic
%{package_path}/include/c++/4.8.3/backward/auto_ptr.h
%{package_path}/include/c++/4.8.3/backward/backward_warning.h
%{package_path}/include/c++/4.8.3/backward/binders.h
%{package_path}/include/c++/4.8.3/backward/hash_fun.h
%{package_path}/include/c++/4.8.3/backward/hash_map
%{package_path}/include/c++/4.8.3/backward/hash_set
%{package_path}/include/c++/4.8.3/backward/hashtable.h
%{package_path}/include/c++/4.8.3/backward/strstream
%{package_path}/include/c++/4.8.3/bits/algorithmfwd.h
%{package_path}/include/c++/4.8.3/bits/alloc_traits.h
%{package_path}/include/c++/4.8.3/bits/allocator.h
%{package_path}/include/c++/4.8.3/bits/atomic_base.h
%{package_path}/include/c++/4.8.3/bits/atomic_lockfree_defines.h
%{package_path}/include/c++/4.8.3/bits/basic_ios.h
%{package_path}/include/c++/4.8.3/bits/basic_ios.tcc
%{package_path}/include/c++/4.8.3/bits/basic_string.h
%{package_path}/include/c++/4.8.3/bits/basic_string.tcc
%{package_path}/include/c++/4.8.3/bits/boost_concept_check.h
%{package_path}/include/c++/4.8.3/bits/c++0x_warning.h
%{package_path}/include/c++/4.8.3/bits/char_traits.h
%{package_path}/include/c++/4.8.3/bits/codecvt.h
%{package_path}/include/c++/4.8.3/bits/concept_check.h
%{package_path}/include/c++/4.8.3/bits/cpp_type_traits.h
%{package_path}/include/c++/4.8.3/bits/cxxabi_forced.h
%{package_path}/include/c++/4.8.3/bits/deque.tcc
%{package_path}/include/c++/4.8.3/bits/exception_defines.h
%{package_path}/include/c++/4.8.3/bits/exception_ptr.h
%{package_path}/include/c++/4.8.3/bits/forward_list.h
%{package_path}/include/c++/4.8.3/bits/forward_list.tcc
%{package_path}/include/c++/4.8.3/bits/fstream.tcc
%{package_path}/include/c++/4.8.3/bits/functexcept.h
%{package_path}/include/c++/4.8.3/bits/functional_hash.h
%{package_path}/include/c++/4.8.3/bits/gslice.h
%{package_path}/include/c++/4.8.3/bits/gslice_array.h
%{package_path}/include/c++/4.8.3/bits/hash_bytes.h
%{package_path}/include/c++/4.8.3/bits/hashtable.h
%{package_path}/include/c++/4.8.3/bits/hashtable_policy.h
%{package_path}/include/c++/4.8.3/bits/indirect_array.h
%{package_path}/include/c++/4.8.3/bits/ios_base.h
%{package_path}/include/c++/4.8.3/bits/istream.tcc
%{package_path}/include/c++/4.8.3/bits/list.tcc
%{package_path}/include/c++/4.8.3/bits/locale_classes.h
%{package_path}/include/c++/4.8.3/bits/locale_classes.tcc
%{package_path}/include/c++/4.8.3/bits/locale_facets.h
%{package_path}/include/c++/4.8.3/bits/locale_facets.tcc
%{package_path}/include/c++/4.8.3/bits/locale_facets_nonio.h
%{package_path}/include/c++/4.8.3/bits/locale_facets_nonio.tcc
%{package_path}/include/c++/4.8.3/bits/localefwd.h
%{package_path}/include/c++/4.8.3/bits/mask_array.h
%{package_path}/include/c++/4.8.3/bits/memoryfwd.h
%{package_path}/include/c++/4.8.3/bits/move.h
%{package_path}/include/c++/4.8.3/bits/nested_exception.h
%{package_path}/include/c++/4.8.3/bits/ostream.tcc
%{package_path}/include/c++/4.8.3/bits/ostream_insert.h
%{package_path}/include/c++/4.8.3/bits/postypes.h
%{package_path}/include/c++/4.8.3/bits/ptr_traits.h
%{package_path}/include/c++/4.8.3/bits/random.h
%{package_path}/include/c++/4.8.3/bits/random.tcc
%{package_path}/include/c++/4.8.3/bits/range_access.h
%{package_path}/include/c++/4.8.3/bits/regex.h
%{package_path}/include/c++/4.8.3/bits/regex_compiler.h
%{package_path}/include/c++/4.8.3/bits/regex_constants.h
%{package_path}/include/c++/4.8.3/bits/regex_cursor.h
%{package_path}/include/c++/4.8.3/bits/regex_error.h
%{package_path}/include/c++/4.8.3/bits/regex_grep_matcher.h
%{package_path}/include/c++/4.8.3/bits/regex_grep_matcher.tcc
%{package_path}/include/c++/4.8.3/bits/regex_nfa.h
%{package_path}/include/c++/4.8.3/bits/regex_nfa.tcc
%{package_path}/include/c++/4.8.3/bits/shared_ptr.h
%{package_path}/include/c++/4.8.3/bits/shared_ptr_base.h
%{package_path}/include/c++/4.8.3/bits/slice_array.h
%{package_path}/include/c++/4.8.3/bits/sstream.tcc
%{package_path}/include/c++/4.8.3/bits/stl_algo.h
%{package_path}/include/c++/4.8.3/bits/stl_algobase.h
%{package_path}/include/c++/4.8.3/bits/stl_bvector.h
%{package_path}/include/c++/4.8.3/bits/stl_construct.h
%{package_path}/include/c++/4.8.3/bits/stl_deque.h
%{package_path}/include/c++/4.8.3/bits/stl_function.h
%{package_path}/include/c++/4.8.3/bits/stl_heap.h
%{package_path}/include/c++/4.8.3/bits/stl_iterator.h
%{package_path}/include/c++/4.8.3/bits/stl_iterator_base_funcs.h
%{package_path}/include/c++/4.8.3/bits/stl_iterator_base_types.h
%{package_path}/include/c++/4.8.3/bits/stl_list.h
%{package_path}/include/c++/4.8.3/bits/stl_map.h
%{package_path}/include/c++/4.8.3/bits/stl_multimap.h
%{package_path}/include/c++/4.8.3/bits/stl_multiset.h
%{package_path}/include/c++/4.8.3/bits/stl_numeric.h
%{package_path}/include/c++/4.8.3/bits/stl_pair.h
%{package_path}/include/c++/4.8.3/bits/stl_queue.h
%{package_path}/include/c++/4.8.3/bits/stl_raw_storage_iter.h
%{package_path}/include/c++/4.8.3/bits/stl_relops.h
%{package_path}/include/c++/4.8.3/bits/stl_set.h
%{package_path}/include/c++/4.8.3/bits/stl_stack.h
%{package_path}/include/c++/4.8.3/bits/stl_tempbuf.h
%{package_path}/include/c++/4.8.3/bits/stl_tree.h
%{package_path}/include/c++/4.8.3/bits/stl_uninitialized.h
%{package_path}/include/c++/4.8.3/bits/stl_vector.h
%{package_path}/include/c++/4.8.3/bits/stream_iterator.h
%{package_path}/include/c++/4.8.3/bits/streambuf.tcc
%{package_path}/include/c++/4.8.3/bits/streambuf_iterator.h
%{package_path}/include/c++/4.8.3/bits/stringfwd.h
%{package_path}/include/c++/4.8.3/bits/unique_ptr.h
%{package_path}/include/c++/4.8.3/bits/unordered_map.h
%{package_path}/include/c++/4.8.3/bits/unordered_set.h
%{package_path}/include/c++/4.8.3/bits/uses_allocator.h
%{package_path}/include/c++/4.8.3/bits/valarray_after.h
%{package_path}/include/c++/4.8.3/bits/valarray_array.h
%{package_path}/include/c++/4.8.3/bits/valarray_array.tcc
%{package_path}/include/c++/4.8.3/bits/valarray_before.h
%{package_path}/include/c++/4.8.3/bits/vector.tcc
%{package_path}/include/c++/4.8.3/bitset
%{package_path}/include/c++/4.8.3/cassert
%{package_path}/include/c++/4.8.3/ccomplex
%{package_path}/include/c++/4.8.3/cctype
%{package_path}/include/c++/4.8.3/cerrno
%{package_path}/include/c++/4.8.3/cfenv
%{package_path}/include/c++/4.8.3/cfloat
%{package_path}/include/c++/4.8.3/chrono
%{package_path}/include/c++/4.8.3/cinttypes
%{package_path}/include/c++/4.8.3/ciso646
%{package_path}/include/c++/4.8.3/climits
%{package_path}/include/c++/4.8.3/clocale
%{package_path}/include/c++/4.8.3/cmath
%{package_path}/include/c++/4.8.3/complex
%{package_path}/include/c++/4.8.3/complex.h
%{package_path}/include/c++/4.8.3/condition_variable
%{package_path}/include/c++/4.8.3/csetjmp
%{package_path}/include/c++/4.8.3/csignal
%{package_path}/include/c++/4.8.3/cstdalign
%{package_path}/include/c++/4.8.3/cstdarg
%{package_path}/include/c++/4.8.3/cstdbool
%{package_path}/include/c++/4.8.3/cstddef
%{package_path}/include/c++/4.8.3/cstdint
%{package_path}/include/c++/4.8.3/cstdio
%{package_path}/include/c++/4.8.3/cstdlib
%{package_path}/include/c++/4.8.3/cstring
%{package_path}/include/c++/4.8.3/ctgmath
%{package_path}/include/c++/4.8.3/ctime
%{package_path}/include/c++/4.8.3/cwchar
%{package_path}/include/c++/4.8.3/cwctype
%{package_path}/include/c++/4.8.3/cxxabi.h
%{package_path}/include/c++/4.8.3/debug/array
%{package_path}/include/c++/4.8.3/debug/bitset
%{package_path}/include/c++/4.8.3/debug/debug.h
%{package_path}/include/c++/4.8.3/debug/deque
%{package_path}/include/c++/4.8.3/debug/formatter.h
%{package_path}/include/c++/4.8.3/debug/forward_list
%{package_path}/include/c++/4.8.3/debug/functions.h
%{package_path}/include/c++/4.8.3/debug/list
%{package_path}/include/c++/4.8.3/debug/macros.h
%{package_path}/include/c++/4.8.3/debug/map
%{package_path}/include/c++/4.8.3/debug/map.h
%{package_path}/include/c++/4.8.3/debug/multimap.h
%{package_path}/include/c++/4.8.3/debug/multiset.h
%{package_path}/include/c++/4.8.3/debug/safe_base.h
%{package_path}/include/c++/4.8.3/debug/safe_iterator.h
%{package_path}/include/c++/4.8.3/debug/safe_iterator.tcc
%{package_path}/include/c++/4.8.3/debug/safe_local_iterator.h
%{package_path}/include/c++/4.8.3/debug/safe_local_iterator.tcc
%{package_path}/include/c++/4.8.3/debug/safe_sequence.h
%{package_path}/include/c++/4.8.3/debug/safe_sequence.tcc
%{package_path}/include/c++/4.8.3/debug/safe_unordered_base.h
%{package_path}/include/c++/4.8.3/debug/safe_unordered_container.h
%{package_path}/include/c++/4.8.3/debug/safe_unordered_container.tcc
%{package_path}/include/c++/4.8.3/debug/set
%{package_path}/include/c++/4.8.3/debug/set.h
%{package_path}/include/c++/4.8.3/debug/string
%{package_path}/include/c++/4.8.3/debug/unordered_map
%{package_path}/include/c++/4.8.3/debug/unordered_set
%{package_path}/include/c++/4.8.3/debug/vector
%{package_path}/include/c++/4.8.3/decimal/decimal
%{package_path}/include/c++/4.8.3/decimal/decimal.h
%{package_path}/include/c++/4.8.3/deque
%{package_path}/include/c++/4.8.3/exception
%{package_path}/include/c++/4.8.3/ext/algorithm
%{package_path}/include/c++/4.8.3/ext/alloc_traits.h
%{package_path}/include/c++/4.8.3/ext/array_allocator.h
%{package_path}/include/c++/4.8.3/ext/atomicity.h
%{package_path}/include/c++/4.8.3/ext/bitmap_allocator.h
%{package_path}/include/c++/4.8.3/ext/cast.h
%{package_path}/include/c++/4.8.3/ext/cmath
%{package_path}/include/c++/4.8.3/ext/codecvt_specializations.h
%{package_path}/include/c++/4.8.3/ext/concurrence.h
%{package_path}/include/c++/4.8.3/ext/debug_allocator.h
%{package_path}/include/c++/4.8.3/ext/enc_filebuf.h
%{package_path}/include/c++/4.8.3/ext/extptr_allocator.h
%{package_path}/include/c++/4.8.3/ext/functional
%{package_path}/include/c++/4.8.3/ext/hash_map
%{package_path}/include/c++/4.8.3/ext/hash_set
%{package_path}/include/c++/4.8.3/ext/iterator
%{package_path}/include/c++/4.8.3/ext/malloc_allocator.h
%{package_path}/include/c++/4.8.3/ext/memory
%{package_path}/include/c++/4.8.3/ext/mt_allocator.h
%{package_path}/include/c++/4.8.3/ext/new_allocator.h
%{package_path}/include/c++/4.8.3/ext/numeric
%{package_path}/include/c++/4.8.3/ext/numeric_traits.h
%{package_path}/include/c++/4.8.3/ext/pb_ds/assoc_container.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/bin_search_tree_/bin_search_tree_.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/bin_search_tree_/constructors_destructor_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/bin_search_tree_/debug_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/bin_search_tree_/erase_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/bin_search_tree_/find_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/bin_search_tree_/info_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/bin_search_tree_/insert_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/bin_search_tree_/iterators_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/bin_search_tree_/node_iterators.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/bin_search_tree_/point_iterators.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/bin_search_tree_/policy_access_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/bin_search_tree_/r_erase_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/bin_search_tree_/rotate_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/bin_search_tree_/split_join_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/bin_search_tree_/traits.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/binary_heap_/binary_heap_.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/binary_heap_/const_iterator.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/binary_heap_/constructors_destructor_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/binary_heap_/debug_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/binary_heap_/entry_cmp.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/binary_heap_/entry_pred.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/binary_heap_/erase_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/binary_heap_/find_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/binary_heap_/info_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/binary_heap_/insert_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/binary_heap_/iterators_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/binary_heap_/point_const_iterator.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/binary_heap_/policy_access_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/binary_heap_/resize_policy.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/binary_heap_/split_join_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/binary_heap_/trace_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/binomial_heap_/binomial_heap_.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/binomial_heap_/constructors_destructor_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/binomial_heap_/debug_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/binomial_heap_base_/binomial_heap_base_.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/binomial_heap_base_/constructors_destructor_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/binomial_heap_base_/debug_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/binomial_heap_base_/erase_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/binomial_heap_base_/find_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/binomial_heap_base_/insert_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/binomial_heap_base_/split_join_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/branch_policy/branch_policy.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/branch_policy/null_node_metadata.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/branch_policy/traits.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/cc_hash_table_map_/cc_ht_map_.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/cc_hash_table_map_/cmp_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/cc_hash_table_map_/cond_key_dtor_entry_dealtor.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/cc_hash_table_map_/constructor_destructor_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/cc_hash_table_map_/constructor_destructor_no_store_hash_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/cc_hash_table_map_/constructor_destructor_store_hash_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/cc_hash_table_map_/debug_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/cc_hash_table_map_/debug_no_store_hash_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/cc_hash_table_map_/debug_store_hash_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/cc_hash_table_map_/entry_list_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/cc_hash_table_map_/erase_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/cc_hash_table_map_/erase_no_store_hash_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/cc_hash_table_map_/erase_store_hash_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/cc_hash_table_map_/find_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/cc_hash_table_map_/find_store_hash_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/cc_hash_table_map_/info_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/cc_hash_table_map_/insert_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/cc_hash_table_map_/insert_no_store_hash_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/cc_hash_table_map_/insert_store_hash_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/cc_hash_table_map_/iterators_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/cc_hash_table_map_/policy_access_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/cc_hash_table_map_/resize_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/cc_hash_table_map_/resize_no_store_hash_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/cc_hash_table_map_/resize_store_hash_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/cc_hash_table_map_/size_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/cc_hash_table_map_/trace_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/cond_dealtor.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/container_base_dispatch.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/debug_map_base.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/eq_fn/eq_by_less.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/eq_fn/hash_eq_fn.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/gp_hash_table_map_/constructor_destructor_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/gp_hash_table_map_/constructor_destructor_no_store_hash_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/gp_hash_table_map_/constructor_destructor_store_hash_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/gp_hash_table_map_/debug_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/gp_hash_table_map_/debug_no_store_hash_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/gp_hash_table_map_/debug_store_hash_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/gp_hash_table_map_/erase_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/gp_hash_table_map_/erase_no_store_hash_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/gp_hash_table_map_/erase_store_hash_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/gp_hash_table_map_/find_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/gp_hash_table_map_/find_no_store_hash_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/gp_hash_table_map_/find_store_hash_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/gp_hash_table_map_/gp_ht_map_.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/gp_hash_table_map_/info_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/gp_hash_table_map_/insert_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/gp_hash_table_map_/insert_no_store_hash_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/gp_hash_table_map_/insert_store_hash_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/gp_hash_table_map_/iterator_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/gp_hash_table_map_/policy_access_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/gp_hash_table_map_/resize_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/gp_hash_table_map_/resize_no_store_hash_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/gp_hash_table_map_/resize_store_hash_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/gp_hash_table_map_/trace_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/hash_fn/direct_mask_range_hashing_imp.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/hash_fn/direct_mod_range_hashing_imp.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/hash_fn/linear_probe_fn_imp.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/hash_fn/mask_based_range_hashing.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/hash_fn/mod_based_range_hashing.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/hash_fn/probe_fn_base.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/hash_fn/quadratic_probe_fn_imp.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/hash_fn/ranged_hash_fn.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/hash_fn/ranged_probe_fn.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/hash_fn/sample_probe_fn.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/hash_fn/sample_range_hashing.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/hash_fn/sample_ranged_hash_fn.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/hash_fn/sample_ranged_probe_fn.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/left_child_next_sibling_heap_/const_iterator.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/left_child_next_sibling_heap_/constructors_destructor_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/left_child_next_sibling_heap_/debug_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/left_child_next_sibling_heap_/erase_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/left_child_next_sibling_heap_/info_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/left_child_next_sibling_heap_/insert_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/left_child_next_sibling_heap_/iterators_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/left_child_next_sibling_heap_/left_child_next_sibling_heap_.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/left_child_next_sibling_heap_/node.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/left_child_next_sibling_heap_/point_const_iterator.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/left_child_next_sibling_heap_/policy_access_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/left_child_next_sibling_heap_/trace_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/list_update_map_/constructor_destructor_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/list_update_map_/debug_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/list_update_map_/entry_metadata_base.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/list_update_map_/erase_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/list_update_map_/find_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/list_update_map_/info_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/list_update_map_/insert_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/list_update_map_/iterators_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/list_update_map_/lu_map_.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/list_update_map_/trace_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/list_update_policy/lu_counter_metadata.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/list_update_policy/sample_update_policy.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/ov_tree_map_/constructors_destructor_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/ov_tree_map_/debug_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/ov_tree_map_/erase_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/ov_tree_map_/info_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/ov_tree_map_/insert_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/ov_tree_map_/iterators_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/ov_tree_map_/node_iterators.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/ov_tree_map_/ov_tree_map_.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/ov_tree_map_/policy_access_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/ov_tree_map_/split_join_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/ov_tree_map_/traits.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/pairing_heap_/constructors_destructor_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/pairing_heap_/debug_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/pairing_heap_/erase_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/pairing_heap_/find_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/pairing_heap_/insert_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/pairing_heap_/pairing_heap_.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/pairing_heap_/split_join_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/pat_trie_/constructors_destructor_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/pat_trie_/debug_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/pat_trie_/erase_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/pat_trie_/find_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/pat_trie_/info_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/pat_trie_/insert_join_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/pat_trie_/iterators_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/pat_trie_/pat_trie_.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/pat_trie_/pat_trie_base.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/pat_trie_/policy_access_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/pat_trie_/r_erase_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/pat_trie_/rotate_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/pat_trie_/split_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/pat_trie_/synth_access_traits.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/pat_trie_/trace_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/pat_trie_/traits.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/pat_trie_/update_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/priority_queue_base_dispatch.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/rb_tree_map_/constructors_destructor_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/rb_tree_map_/debug_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/rb_tree_map_/erase_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/rb_tree_map_/find_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/rb_tree_map_/info_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/rb_tree_map_/insert_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/rb_tree_map_/node.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/rb_tree_map_/rb_tree_.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/rb_tree_map_/split_join_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/rb_tree_map_/traits.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/rc_binomial_heap_/constructors_destructor_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/rc_binomial_heap_/debug_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/rc_binomial_heap_/erase_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/rc_binomial_heap_/insert_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/rc_binomial_heap_/rc.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/rc_binomial_heap_/rc_binomial_heap_.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/rc_binomial_heap_/split_join_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/rc_binomial_heap_/trace_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/resize_policy/cc_hash_max_collision_check_resize_trigger_imp.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/resize_policy/hash_exponential_size_policy_imp.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/resize_policy/hash_load_check_resize_trigger_imp.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/resize_policy/hash_load_check_resize_trigger_size_base.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/resize_policy/hash_prime_size_policy_imp.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/resize_policy/hash_standard_resize_policy_imp.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/resize_policy/sample_resize_policy.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/resize_policy/sample_resize_trigger.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/resize_policy/sample_size_policy.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/splay_tree_/constructors_destructor_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/splay_tree_/debug_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/splay_tree_/erase_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/splay_tree_/find_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/splay_tree_/info_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/splay_tree_/insert_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/splay_tree_/node.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/splay_tree_/splay_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/splay_tree_/splay_tree_.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/splay_tree_/split_join_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/splay_tree_/traits.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/standard_policies.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/thin_heap_/constructors_destructor_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/thin_heap_/debug_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/thin_heap_/erase_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/thin_heap_/find_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/thin_heap_/insert_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/thin_heap_/split_join_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/thin_heap_/thin_heap_.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/thin_heap_/trace_fn_imps.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/tree_policy/node_metadata_selector.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/tree_policy/order_statistics_imp.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/tree_policy/sample_tree_node_update.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/tree_trace_base.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/trie_policy/node_metadata_selector.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/trie_policy/order_statistics_imp.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/trie_policy/prefix_search_node_update_imp.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/trie_policy/sample_trie_access_traits.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/trie_policy/sample_trie_node_update.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/trie_policy/trie_policy_base.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/trie_policy/trie_string_access_traits_imp.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/type_utils.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/types_traits.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/unordered_iterator/const_iterator.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/unordered_iterator/iterator.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/unordered_iterator/point_const_iterator.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/detail/unordered_iterator/point_iterator.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/exception.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/hash_policy.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/list_update_policy.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/priority_queue.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/tag_and_trait.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/tree_policy.hpp
%{package_path}/include/c++/4.8.3/ext/pb_ds/trie_policy.hpp
%{package_path}/include/c++/4.8.3/ext/pod_char_traits.h
%{package_path}/include/c++/4.8.3/ext/pointer.h
%{package_path}/include/c++/4.8.3/ext/pool_allocator.h
%{package_path}/include/c++/4.8.3/ext/random
%{package_path}/include/c++/4.8.3/ext/random.tcc
%{package_path}/include/c++/4.8.3/ext/rb_tree
%{package_path}/include/c++/4.8.3/ext/rc_string_base.h
%{package_path}/include/c++/4.8.3/ext/rope
%{package_path}/include/c++/4.8.3/ext/ropeimpl.h
%{package_path}/include/c++/4.8.3/ext/slist
%{package_path}/include/c++/4.8.3/ext/sso_string_base.h
%{package_path}/include/c++/4.8.3/ext/stdio_filebuf.h
%{package_path}/include/c++/4.8.3/ext/stdio_sync_filebuf.h
%{package_path}/include/c++/4.8.3/ext/string_conversions.h
%{package_path}/include/c++/4.8.3/ext/throw_allocator.h
%{package_path}/include/c++/4.8.3/ext/type_traits.h
%{package_path}/include/c++/4.8.3/ext/typelist.h
%{package_path}/include/c++/4.8.3/ext/vstring.h
%{package_path}/include/c++/4.8.3/ext/vstring.tcc
%{package_path}/include/c++/4.8.3/ext/vstring_fwd.h
%{package_path}/include/c++/4.8.3/ext/vstring_util.h
%{package_path}/include/c++/4.8.3/fenv.h
%{package_path}/include/c++/4.8.3/forward_list
%{package_path}/include/c++/4.8.3/fstream
%{package_path}/include/c++/4.8.3/functional
%{package_path}/include/c++/4.8.3/future
%{package_path}/include/c++/4.8.3/initializer_list
%{package_path}/include/c++/4.8.3/iomanip
%{package_path}/include/c++/4.8.3/ios
%{package_path}/include/c++/4.8.3/iosfwd
%{package_path}/include/c++/4.8.3/iostream
%{package_path}/include/c++/4.8.3/istream
%{package_path}/include/c++/4.8.3/iterator
%{package_path}/include/c++/4.8.3/limits
%{package_path}/include/c++/4.8.3/list
%{package_path}/include/c++/4.8.3/locale
%{package_path}/include/c++/4.8.3/map
%{package_path}/include/c++/4.8.3/memory
%{package_path}/include/c++/4.8.3/mutex
%{package_path}/include/c++/4.8.3/new
%{package_path}/include/c++/4.8.3/numeric
%{package_path}/include/c++/4.8.3/ostream
%{package_path}/include/c++/4.8.3/parallel/algo.h
%{package_path}/include/c++/4.8.3/parallel/algobase.h
%{package_path}/include/c++/4.8.3/parallel/algorithm
%{package_path}/include/c++/4.8.3/parallel/algorithmfwd.h
%{package_path}/include/c++/4.8.3/parallel/balanced_quicksort.h
%{package_path}/include/c++/4.8.3/parallel/base.h
%{package_path}/include/c++/4.8.3/parallel/basic_iterator.h
%{package_path}/include/c++/4.8.3/parallel/checkers.h
%{package_path}/include/c++/4.8.3/parallel/compatibility.h
%{package_path}/include/c++/4.8.3/parallel/compiletime_settings.h
%{package_path}/include/c++/4.8.3/parallel/equally_split.h
%{package_path}/include/c++/4.8.3/parallel/features.h
%{package_path}/include/c++/4.8.3/parallel/find.h
%{package_path}/include/c++/4.8.3/parallel/find_selectors.h
%{package_path}/include/c++/4.8.3/parallel/for_each.h
%{package_path}/include/c++/4.8.3/parallel/for_each_selectors.h
%{package_path}/include/c++/4.8.3/parallel/iterator.h
%{package_path}/include/c++/4.8.3/parallel/list_partition.h
%{package_path}/include/c++/4.8.3/parallel/losertree.h
%{package_path}/include/c++/4.8.3/parallel/merge.h
%{package_path}/include/c++/4.8.3/parallel/multiseq_selection.h
%{package_path}/include/c++/4.8.3/parallel/multiway_merge.h
%{package_path}/include/c++/4.8.3/parallel/multiway_mergesort.h
%{package_path}/include/c++/4.8.3/parallel/numeric
%{package_path}/include/c++/4.8.3/parallel/numericfwd.h
%{package_path}/include/c++/4.8.3/parallel/omp_loop.h
%{package_path}/include/c++/4.8.3/parallel/omp_loop_static.h
%{package_path}/include/c++/4.8.3/parallel/par_loop.h
%{package_path}/include/c++/4.8.3/parallel/parallel.h
%{package_path}/include/c++/4.8.3/parallel/partial_sum.h
%{package_path}/include/c++/4.8.3/parallel/partition.h
%{package_path}/include/c++/4.8.3/parallel/queue.h
%{package_path}/include/c++/4.8.3/parallel/quicksort.h
%{package_path}/include/c++/4.8.3/parallel/random_number.h
%{package_path}/include/c++/4.8.3/parallel/random_shuffle.h
%{package_path}/include/c++/4.8.3/parallel/search.h
%{package_path}/include/c++/4.8.3/parallel/set_operations.h
%{package_path}/include/c++/4.8.3/parallel/settings.h
%{package_path}/include/c++/4.8.3/parallel/sort.h
%{package_path}/include/c++/4.8.3/parallel/tags.h
%{package_path}/include/c++/4.8.3/parallel/types.h
%{package_path}/include/c++/4.8.3/parallel/unique_copy.h
%{package_path}/include/c++/4.8.3/parallel/workstealing.h
%{package_path}/include/c++/4.8.3/profile/array
%{package_path}/include/c++/4.8.3/profile/base.h
%{package_path}/include/c++/4.8.3/profile/bitset
%{package_path}/include/c++/4.8.3/profile/deque
%{package_path}/include/c++/4.8.3/profile/forward_list
%{package_path}/include/c++/4.8.3/profile/impl/profiler.h
%{package_path}/include/c++/4.8.3/profile/impl/profiler_algos.h
%{package_path}/include/c++/4.8.3/profile/impl/profiler_container_size.h
%{package_path}/include/c++/4.8.3/profile/impl/profiler_hash_func.h
%{package_path}/include/c++/4.8.3/profile/impl/profiler_hashtable_size.h
%{package_path}/include/c++/4.8.3/profile/impl/profiler_list_to_slist.h
%{package_path}/include/c++/4.8.3/profile/impl/profiler_list_to_vector.h
%{package_path}/include/c++/4.8.3/profile/impl/profiler_map_to_unordered_map.h
%{package_path}/include/c++/4.8.3/profile/impl/profiler_node.h
%{package_path}/include/c++/4.8.3/profile/impl/profiler_state.h
%{package_path}/include/c++/4.8.3/profile/impl/profiler_trace.h
%{package_path}/include/c++/4.8.3/profile/impl/profiler_vector_size.h
%{package_path}/include/c++/4.8.3/profile/impl/profiler_vector_to_list.h
%{package_path}/include/c++/4.8.3/profile/iterator_tracker.h
%{package_path}/include/c++/4.8.3/profile/list
%{package_path}/include/c++/4.8.3/profile/map
%{package_path}/include/c++/4.8.3/profile/map.h
%{package_path}/include/c++/4.8.3/profile/multimap.h
%{package_path}/include/c++/4.8.3/profile/multiset.h
%{package_path}/include/c++/4.8.3/profile/set
%{package_path}/include/c++/4.8.3/profile/set.h
%{package_path}/include/c++/4.8.3/profile/unordered_base.h
%{package_path}/include/c++/4.8.3/profile/unordered_map
%{package_path}/include/c++/4.8.3/profile/unordered_set
%{package_path}/include/c++/4.8.3/profile/vector
%{package_path}/include/c++/4.8.3/queue
%{package_path}/include/c++/4.8.3/random
%{package_path}/include/c++/4.8.3/ratio
%{package_path}/include/c++/4.8.3/regex
%{package_path}/include/c++/4.8.3/scoped_allocator
%{package_path}/include/c++/4.8.3/set
%{package_path}/include/c++/4.8.3/sstream
%{package_path}/include/c++/4.8.3/stack
%{package_path}/include/c++/4.8.3/stdexcept
%{package_path}/include/c++/4.8.3/streambuf
%{package_path}/include/c++/4.8.3/string
%{package_path}/include/c++/4.8.3/system_error
%{package_path}/include/c++/4.8.3/tgmath.h
%{package_path}/include/c++/4.8.3/thread
%{package_path}/include/c++/4.8.3/tr1/array
%{package_path}/include/c++/4.8.3/tr1/bessel_function.tcc
%{package_path}/include/c++/4.8.3/tr1/beta_function.tcc
%{package_path}/include/c++/4.8.3/tr1/ccomplex
%{package_path}/include/c++/4.8.3/tr1/cctype
%{package_path}/include/c++/4.8.3/tr1/cfenv
%{package_path}/include/c++/4.8.3/tr1/cfloat
%{package_path}/include/c++/4.8.3/tr1/cinttypes
%{package_path}/include/c++/4.8.3/tr1/climits
%{package_path}/include/c++/4.8.3/tr1/cmath
%{package_path}/include/c++/4.8.3/tr1/complex
%{package_path}/include/c++/4.8.3/tr1/complex.h
%{package_path}/include/c++/4.8.3/tr1/cstdarg
%{package_path}/include/c++/4.8.3/tr1/cstdbool
%{package_path}/include/c++/4.8.3/tr1/cstdint
%{package_path}/include/c++/4.8.3/tr1/cstdio
%{package_path}/include/c++/4.8.3/tr1/cstdlib
%{package_path}/include/c++/4.8.3/tr1/ctgmath
%{package_path}/include/c++/4.8.3/tr1/ctime
%{package_path}/include/c++/4.8.3/tr1/ctype.h
%{package_path}/include/c++/4.8.3/tr1/cwchar
%{package_path}/include/c++/4.8.3/tr1/cwctype
%{package_path}/include/c++/4.8.3/tr1/ell_integral.tcc
%{package_path}/include/c++/4.8.3/tr1/exp_integral.tcc
%{package_path}/include/c++/4.8.3/tr1/fenv.h
%{package_path}/include/c++/4.8.3/tr1/float.h
%{package_path}/include/c++/4.8.3/tr1/functional
%{package_path}/include/c++/4.8.3/tr1/functional_hash.h
%{package_path}/include/c++/4.8.3/tr1/gamma.tcc
%{package_path}/include/c++/4.8.3/tr1/hashtable.h
%{package_path}/include/c++/4.8.3/tr1/hashtable_policy.h
%{package_path}/include/c++/4.8.3/tr1/hypergeometric.tcc
%{package_path}/include/c++/4.8.3/tr1/inttypes.h
%{package_path}/include/c++/4.8.3/tr1/legendre_function.tcc
%{package_path}/include/c++/4.8.3/tr1/limits.h
%{package_path}/include/c++/4.8.3/tr1/math.h
%{package_path}/include/c++/4.8.3/tr1/memory
%{package_path}/include/c++/4.8.3/tr1/modified_bessel_func.tcc
%{package_path}/include/c++/4.8.3/tr1/poly_hermite.tcc
%{package_path}/include/c++/4.8.3/tr1/poly_laguerre.tcc
%{package_path}/include/c++/4.8.3/tr1/random
%{package_path}/include/c++/4.8.3/tr1/random.h
%{package_path}/include/c++/4.8.3/tr1/random.tcc
%{package_path}/include/c++/4.8.3/tr1/regex
%{package_path}/include/c++/4.8.3/tr1/riemann_zeta.tcc
%{package_path}/include/c++/4.8.3/tr1/shared_ptr.h
%{package_path}/include/c++/4.8.3/tr1/special_function_util.h
%{package_path}/include/c++/4.8.3/tr1/stdarg.h
%{package_path}/include/c++/4.8.3/tr1/stdbool.h
%{package_path}/include/c++/4.8.3/tr1/stdint.h
%{package_path}/include/c++/4.8.3/tr1/stdio.h
%{package_path}/include/c++/4.8.3/tr1/stdlib.h
%{package_path}/include/c++/4.8.3/tr1/tgmath.h
%{package_path}/include/c++/4.8.3/tr1/tuple
%{package_path}/include/c++/4.8.3/tr1/type_traits
%{package_path}/include/c++/4.8.3/tr1/unordered_map
%{package_path}/include/c++/4.8.3/tr1/unordered_map.h
%{package_path}/include/c++/4.8.3/tr1/unordered_set
%{package_path}/include/c++/4.8.3/tr1/unordered_set.h
%{package_path}/include/c++/4.8.3/tr1/utility
%{package_path}/include/c++/4.8.3/tr1/wchar.h
%{package_path}/include/c++/4.8.3/tr1/wctype.h
%{package_path}/include/c++/4.8.3/tr2/bool_set
%{package_path}/include/c++/4.8.3/tr2/bool_set.tcc
%{package_path}/include/c++/4.8.3/tr2/dynamic_bitset
%{package_path}/include/c++/4.8.3/tr2/ratio
%{package_path}/include/c++/4.8.3/tr2/type_traits
%{package_path}/include/c++/4.8.3/tuple
%{package_path}/include/c++/4.8.3/type_traits
%{package_path}/include/c++/4.8.3/typeindex
%{package_path}/include/c++/4.8.3/typeinfo
%{package_path}/include/c++/4.8.3/unordered_map
%{package_path}/include/c++/4.8.3/unordered_set
%{package_path}/include/c++/4.8.3/utility
%{package_path}/include/c++/4.8.3/valarray
%{package_path}/include/c++/4.8.3/vector
%{package_path}/include/c++/4.8.3/x86_64-redhat-linux/bits/atomic_word.h
%{package_path}/include/c++/4.8.3/x86_64-redhat-linux/bits/basic_file.h
%{package_path}/include/c++/4.8.3/x86_64-redhat-linux/bits/c++allocator.h
%{package_path}/include/c++/4.8.3/x86_64-redhat-linux/bits/c++config.h
%{package_path}/include/c++/4.8.3/x86_64-redhat-linux/bits/c++io.h
%{package_path}/include/c++/4.8.3/x86_64-redhat-linux/bits/c++locale.h
%{package_path}/include/c++/4.8.3/x86_64-redhat-linux/bits/cpu_defines.h
%{package_path}/include/c++/4.8.3/x86_64-redhat-linux/bits/ctype_base.h
%{package_path}/include/c++/4.8.3/x86_64-redhat-linux/bits/ctype_inline.h
%{package_path}/include/c++/4.8.3/x86_64-redhat-linux/bits/cxxabi_tweaks.h
%{package_path}/include/c++/4.8.3/x86_64-redhat-linux/bits/error_constants.h
%{package_path}/include/c++/4.8.3/x86_64-redhat-linux/bits/extc++.h
%{package_path}/include/c++/4.8.3/x86_64-redhat-linux/bits/gthr-default.h
%{package_path}/include/c++/4.8.3/x86_64-redhat-linux/bits/gthr-posix.h
%{package_path}/include/c++/4.8.3/x86_64-redhat-linux/bits/gthr-single.h
%{package_path}/include/c++/4.8.3/x86_64-redhat-linux/bits/gthr.h
%{package_path}/include/c++/4.8.3/x86_64-redhat-linux/bits/messages_members.h
%{package_path}/include/c++/4.8.3/x86_64-redhat-linux/bits/opt_random.h
%{package_path}/include/c++/4.8.3/x86_64-redhat-linux/bits/os_defines.h
%{package_path}/include/c++/4.8.3/x86_64-redhat-linux/bits/stdc++.h
%{package_path}/include/c++/4.8.3/x86_64-redhat-linux/bits/stdtr1c++.h
%{package_path}/include/c++/4.8.3/x86_64-redhat-linux/bits/time_members.h
%{package_path}/include/c++/4.8.3/x86_64-redhat-linux/ext/opt_random.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/crtbegin.o
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/crtbeginS.o
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/crtbeginT.o
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/crtend.o
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/crtendS.o
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/crtfastmath.o
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/crtprec32.o
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/crtprec64.o
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/crtprec80.o
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/finclude/omp_lib.f90
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/finclude/omp_lib.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/finclude/omp_lib.mod
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/finclude/omp_lib_kinds.mod
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include-fixed/README
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include-fixed/limits.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include-fixed/syslimits.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/adxintrin.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/ammintrin.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/avx2intrin.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/avxintrin.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/bmi2intrin.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/bmiintrin.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/bmmintrin.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/cpuid.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/cross-stdarg.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/emmintrin.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/f16cintrin.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/float.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/fma4intrin.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/fmaintrin.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/fxsrintrin.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/ia32intrin.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/immintrin.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/iso646.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/lwpintrin.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/lzcntintrin.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/mm3dnow.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/mm_malloc.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/mmintrin.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/nmmintrin.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/objc/NXConstStr.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/objc/Object.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/objc/Protocol.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/objc/message.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/objc/objc-decls.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/objc/objc-exception.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/objc/objc-sync.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/objc/objc.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/objc/runtime.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/objc/thr.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/omp.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/pmmintrin.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/popcntintrin.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/prfchwintrin.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/quadmath.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/quadmath_weak.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/rdseedintrin.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/rtmintrin.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/smmintrin.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/ssp/ssp.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/ssp/stdio.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/ssp/string.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/ssp/unistd.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/stdalign.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/stdarg.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/stdbool.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/stddef.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/stdfix.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/stdint-gcc.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/stdint.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/stdnoreturn.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/tbmintrin.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/tmmintrin.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/unwind.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/varargs.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/wmmintrin.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/x86intrin.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/xmmintrin.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/xopintrin.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/xsaveintrin.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/xsaveoptintrin.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/include/xtestintrin.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/install-tools/fixinc_list
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/install-tools/gsyslimits.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/install-tools/include/README
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/install-tools/include/limits.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/install-tools/macro_list
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/install-tools/mkheaders.conf
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/libcaf_single.a
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/libcaf_single.la
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/libgcc.a
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/libgcc_eh.a
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/libgcov.a
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/libgfortranbegin.a
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/libgfortranbegin.la
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/gtype.state
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/ada/gcc-interface/ada-tree.def
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/alias.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/all-tree.def
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/alloc-pool.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/ansidecl.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/auto-host.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/b-header-vars
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/basic-block.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/bitmap.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/builtins.def
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/bversion.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/c-family/c-common.def
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/c-family/c-common.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/c-family/c-objc.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/c-family/c-pragma.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/c-family/c-pretty-print.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/c-tree.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/cfg-flags.def
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/cfghooks.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/cfgloop.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/cgraph.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/cif-code.def
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/config.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/config/dbxelf.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/config/elfos.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/config/glibc-stdint.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/config/gnu-user.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/config/i386/att.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/config/i386/biarch64.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/config/i386/gnu-user-common.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/config/i386/gnu-user64.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/config/i386/i386-opts.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/config/i386/i386-protos.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/config/i386/i386.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/config/i386/linux-common.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/config/i386/linux64.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/config/i386/ssemath.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/config/i386/unix.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/config/i386/x86-64.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/config/initfini-array.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/config/linux-android.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/config/linux.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/config/vxworks-dummy.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/configargs.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/coretypes.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/cp/cp-tree.def
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/cp/cp-tree.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/cp/cxx-pretty-print.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/cp/name-lookup.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/cppdefault.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/cpplib.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/debug.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/defaults.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/diagnostic-core.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/diagnostic.def
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/diagnostic.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/double-int.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/dumpfile.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/emit-rtl.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/except.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/filenames.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/fixed-value.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/flag-types.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/flags.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/function.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/gcc-plugin.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/genrtl.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/ggc.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/gimple-pretty-print.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/gimple.def
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/gimple.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/gsstruct.def
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/gtm-builtins.def
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/gtype-desc.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/hard-reg-set.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/hashtab.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/highlev-plugin-common.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/hwint.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/incpath.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/input.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/insn-constants.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/insn-flags.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/insn-modes.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/insn-notes.def
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/internal-fn.def
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/internal-fn.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/intl.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/ipa-prop.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/ipa-ref-inline.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/ipa-ref.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/ipa-reference.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/ipa-utils.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/is-a.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/java/java-tree.def
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/langhooks.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/libiberty.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/line-map.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/machmode.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/md5.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/mode-classes.def
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/objc/objc-tree.def
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/obstack.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/omp-builtins.def
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/options.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/opts.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/output.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/params.def
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/params.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/plugin-api.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/plugin-version.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/plugin.def
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/plugin.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/pointer-set.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/predict.def
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/predict.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/prefix.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/pretty-print.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/real.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/realmpfr.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/reg-notes.def
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/rtl.def
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/rtl.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/safe-ctype.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/sanitizer.def
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/sbitmap.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/splay-tree.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/statistics.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/symtab.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/sync-builtins.def
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/system.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/target-hooks-macros.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/target.def
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/target.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/timevar.def
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/timevar.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/tm-preds.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/tm.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/tm_p.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/toplev.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/tree-check.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/tree-dump.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/tree-flow-inline.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/tree-flow.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/tree-inline.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/tree-iterator.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/tree-pass.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/tree-pretty-print.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/tree-ssa-alias.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/tree-ssa-operands.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/tree-ssa-sccvn.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/tree.def
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/tree.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/treestruct.def
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/vec.h
%{package_path}/lib/gcc/x86_64-redhat-linux/4.8.3/plugin/include/version.h
%{package_path}/lib64/libasan.a
%{package_path}/lib64/libasan.la
%{package_path}/lib64/libasan.so
%{package_path}/lib64/libasan.so.0
%{package_path}/lib64/libasan.so.0.0.0
%{package_path}/lib64/libasan_preinit.o
%{package_path}/lib64/libatomic.a
%{package_path}/lib64/libatomic.la
%{package_path}/lib64/libatomic.so
%{package_path}/lib64/libatomic.so.1
%{package_path}/lib64/libatomic.so.1.0.0
%{package_path}/lib64/libgcc_s.so
%{package_path}/lib64/libgcc_s.so.1
%{package_path}/lib64/libgfortran.a
%{package_path}/lib64/libgfortran.la
%{package_path}/lib64/libgfortran.so
%{package_path}/lib64/libgfortran.so.3
%{package_path}/lib64/libgfortran.so.3.0.0
%{package_path}/lib64/libgfortran.spec
%{package_path}/lib64/libgomp.a
%{package_path}/lib64/libgomp.la
%{package_path}/lib64/libgomp.so
%{package_path}/lib64/libgomp.so.1
%{package_path}/lib64/libgomp.so.1.0.0
%{package_path}/lib64/libgomp.spec
%{package_path}/lib64/libiberty.a
%{package_path}/lib64/libitm.a
%{package_path}/lib64/libitm.la
%{package_path}/lib64/libitm.so
%{package_path}/lib64/libitm.so.1
%{package_path}/lib64/libitm.so.1.0.0
%{package_path}/lib64/libitm.spec
%{package_path}/lib64/libobjc.a
%{package_path}/lib64/libobjc.la
%{package_path}/lib64/libobjc.so
%{package_path}/lib64/libobjc.so.4
%{package_path}/lib64/libobjc.so.4.0.0
%{package_path}/lib64/libquadmath.a
%{package_path}/lib64/libquadmath.la
%{package_path}/lib64/libquadmath.so
%{package_path}/lib64/libquadmath.so.0
%{package_path}/lib64/libquadmath.so.0.0.0
%{package_path}/lib64/libssp.a
%{package_path}/lib64/libssp.la
%{package_path}/lib64/libssp.so
%{package_path}/lib64/libssp.so.0
%{package_path}/lib64/libssp.so.0.0.0
%{package_path}/lib64/libssp_nonshared.a
%{package_path}/lib64/libssp_nonshared.la
%{package_path}/lib64/libstdc++.a
%{package_path}/lib64/libstdc++.la
%{package_path}/lib64/libstdc++.so
%{package_path}/lib64/libstdc++.so.6
%{package_path}/lib64/libstdc++.so.6.0.19
%{package_path}/lib64/libstdc++.so.6.0.19-gdb.py
%{package_path}/lib64/libstdc++.so.6.0.19-gdb.pyc
%{package_path}/lib64/libstdc++.so.6.0.19-gdb.pyo
%{package_path}/lib64/libsupc++.a
%{package_path}/lib64/libsupc++.la
%{package_path}/lib64/libtsan.a
%{package_path}/lib64/libtsan.la
%{package_path}/lib64/libtsan.so
%{package_path}/lib64/libtsan.so.0
%{package_path}/lib64/libtsan.so.0.0.0
%{package_path}/libexec/gcc/x86_64-redhat-linux/4.8.3/cc1
%{package_path}/libexec/gcc/x86_64-redhat-linux/4.8.3/cc1obj
%{package_path}/libexec/gcc/x86_64-redhat-linux/4.8.3/cc1objplus
%{package_path}/libexec/gcc/x86_64-redhat-linux/4.8.3/cc1plus
%{package_path}/libexec/gcc/x86_64-redhat-linux/4.8.3/collect2
%{package_path}/libexec/gcc/x86_64-redhat-linux/4.8.3/f951
%{package_path}/libexec/gcc/x86_64-redhat-linux/4.8.3/install-tools/fixinc.sh
%{package_path}/libexec/gcc/x86_64-redhat-linux/4.8.3/install-tools/fixincl
%{package_path}/libexec/gcc/x86_64-redhat-linux/4.8.3/install-tools/mkheaders
%{package_path}/libexec/gcc/x86_64-redhat-linux/4.8.3/install-tools/mkinstalldirs
%{package_path}/libexec/gcc/x86_64-redhat-linux/4.8.3/liblto_plugin.la
%{package_path}/libexec/gcc/x86_64-redhat-linux/4.8.3/liblto_plugin.so
%{package_path}/libexec/gcc/x86_64-redhat-linux/4.8.3/liblto_plugin.so.0
%{package_path}/libexec/gcc/x86_64-redhat-linux/4.8.3/liblto_plugin.so.0.0.0
%{package_path}/libexec/gcc/x86_64-redhat-linux/4.8.3/lto-wrapper
%{package_path}/libexec/gcc/x86_64-redhat-linux/4.8.3/lto1
%{package_path}/libexec/gcc/x86_64-redhat-linux/4.8.3/plugin/gengtype
%{package_path}/share/gcc-4.8.3/python/libstdcxx/__init__.py
%{package_path}/share/gcc-4.8.3/python/libstdcxx/__init__.pyc
%{package_path}/share/gcc-4.8.3/python/libstdcxx/__init__.pyo
%{package_path}/share/gcc-4.8.3/python/libstdcxx/v6/__init__.py
%{package_path}/share/gcc-4.8.3/python/libstdcxx/v6/__init__.pyc
%{package_path}/share/gcc-4.8.3/python/libstdcxx/v6/__init__.pyo
%{package_path}/share/gcc-4.8.3/python/libstdcxx/v6/printers.py
%{package_path}/share/gcc-4.8.3/python/libstdcxx/v6/printers.pyc
%{package_path}/share/gcc-4.8.3/python/libstdcxx/v6/printers.pyo
%{package_path}/share/info/libgomp.info
%{package_path}/share/info/libitm.info
%{package_path}/share/info/libquadmath.info
%{package_path}/share/man/man1/cpp.1
%{package_path}/share/man/man1/g++.1
%{package_path}/share/man/man1/gcc.1
%{package_path}/share/man/man1/gcov.1
%{package_path}/share/man/man1/gfortran.1
%{package_path}/share/man/man7/fsf-funding.7
%{package_path}/share/man/man7/gfdl.7
%{package_path}/share/man/man7/gpl.7
