# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |vagrant|
  vagrant.vm.define "gitlab" do |config|
    config.vm.box = "centos-6.5"
    config.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box"
    config.vm.provision :shell, path: "bootstrap.sh"
    config.vm.hostname = "gitlab.local"
    config.vm.network "private_network", ip: "10.10.1.42"

    config.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.customize ["modifyvm", :id, "--memory", "2048"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--cpus", "2" ]
      vb.customize ["modifyvm", :id, "--ioapic", "on"]
    end
  end
end
