# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |vagrant|
  vagrant.vm.define "gitlab" do |config|
    config.vm.box = "opscode-centos-7.0"
    config.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.0_chef-provisionerless.box"
    config.vm.hostname = "gitlab.local.vm"
    config.vm.network "private_network", ip: "10.10.1.41"

    config.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--cpus", "1" ]
      vb.customize ["modifyvm", :id, "--ioapic", "on"]
    end

    config.vm.provision :shell, path: "bootstrap.sh"
    config.vm.provision :shell, path: "puppet.sh"
  end

  vagrant.vm.define "puppet" do |config|
    config.vm.box = "opscode-centos-7.0"
    config.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.0_chef-provisionerless.box"
    config.vm.hostname = "puppet.local.vm"
    config.vm.network "private_network", ip: "10.10.1.42"

    config.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.customize ["modifyvm", :id, "--memory", "4096"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--cpus", "1" ]
      vb.customize ["modifyvm", :id, "--ioapic", "on"]
    end

    config.vm.provision :shell, path: "bootstrap.sh"
    config.vm.provision :shell, path: "puppet.sh"
  end

  vagrant.vm.define "client" do |config|
    config.vm.box = "opscode-centos-7.0"
    config.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.0_chef-provisionerless.box"
    config.vm.hostname = "client.local.vm"
    config.vm.network "private_network", ip: "10.10.1.43"

    config.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.customize ["modifyvm", :id, "--memory", "512"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--cpus", "1" ]
      vb.customize ["modifyvm", :id, "--ioapic", "on"]
    end

    config.vm.provision :shell, path: "bootstrap.sh"
  end
end
